---
# Download Artifacts

- name: Create Backend App Directory
  file:
    path: ~/backend_app_dir
    state:  directory

- name: Copy Artifacts
  become: true
  copy:
    src:  ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app_dir/artifact.tar.gz


- name: Install Dependencies and Start App
  shell: |
    cd /home/ubuntu/backend_app_dir
    tar xzf artifact.tar.gz
    npm install
    pm2 stop all
    pm2 start npm -- start
  register: pm2
  
- debug: msg="{{ pm2.stdout }}"
